version: '3.7'

services:
  app:
    container_name: toolbox_api
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    working_dir: '/srv/toolbox'
    volumes:
      - './:/srv/toolbox'
    ports:
      - "4000:4000"
    networks:
      - 'toolbox-network'

networks:
  toolbox-network:
    driver: bridge
    name: toolbox
    ipam:
      driver: default
